### ISSUE TITLE
Octopull loops in log in authentication

### ISSUE THREAD

**Issue by Danilodum** [rmhartog/octopull-plugin#2]
My travis build passes and the yml is setup correctly. 

I authenticated octopull once and it seemed to work fine.

I am using checkstyle 2.15 instead of 2.14.

Now octopull doesn't show anything, it gives an authentication error, and pressing log in refreshes the page and shows the same error again

**Comment by Danilodum** [comment]
Update: the loop eventually stops, and the plugin seems to do something (blue loading bar completes), but reporting results are not displayed...

**Comment by rmhartog** [comment]
Hello @Danilodum14,

apologies for the delayed response, I was out of the country. From looking at [this build log](https://travis-ci.org/Denpeer/ContextProject/jobs/62904286) at line 970 I can see that `target/checkstyle-result.xml` does not exist. Please make sure that checkstyle is run and outputs an XML file, and/or update the path in `.travis.yml`

Let me know how that works out!

**Comment by Danilodum** [comment]
Hi @rmhartog 

Octopull works! travis doesn't run mvn site automatically, so the reports weren't generated. 

Adding 'install: - mvn site' before the after_script did the trick. You might want to add that, or make a note on your website, or correct me if this only happened on my end.

Also, adding an overview in the conversation tab of the pull request stating the results of the tools would be much appreciated! (like travis does). Or is there a way to view the results without scrolling through the files changed tab?

Thanks for your help!

**Comment by rmhartog** [comment]
I've updated the setup instructions to make the execution of each plugin more explicit.

Such an overview does not currently exist, but I'll keep it in mind, thank you.
