### ISSUE TITLE
Avast reports plugin as harmful

### ISSUE THREAD

**Issue by TimvdLippe** [rmhartog/octopull-plugin#3]
Avast just reported that Octopull is a harmful AddOn and advised me to remove the AddOn.

![image](https://cloud.githubusercontent.com/assets/5948271/7671904/ae441a88-fce1-11e4-916d-22d65fd05379.png)

**Comment by rmhartog** [comment]
Hello @JeremybellEU,

thanks for reporting this; I will see what I can do about it. However, their warning seems to be based on a 'reputation' of some sort, which doesn't give me much room to improve. Does it tell you anything interesting if you click on 'Details tonen'?

**Comment by TimvdLippe** [comment]
I have yet to receive the popup again. If I do see it again, I will report the details here.

**Comment by rmhartog** [comment]
Thank you, I will leave the issue open, as I'm not sure if I can currently resolve it.

**Comment by TimvdLippe** [comment]
This issue is presumably resolved as I have never seen the popup again. Probably a false positive that was fixed by Avast themselves.

**Comment by rmhartog** [comment]
I appreciate you letting me know, thanks!
